### ISSUE TITLE
Plugin doesn't work with WordPress 4.4 

### ISSUE THREAD

**Issue by picajoso** [iseulde/wp-front-end-editor#271]
The problem continues with WP 4.4. The plugin isn't working there :/

**Comment by 1exp** [comment]
I'm so heartbroken, I love this plugin so much.

**Comment by iseulde** [comment]
Could you help test? Determine what's broken and see if issues are fixed? Make tickets for them? :) Thanks!

**Comment by picajoso** [comment]
I applied some of the fixes that r-a-y tried to make to the plugin. It is partially working under 4.4.1: 

- You can edit on the front editor, shortcuts work
- The button bar doesn't appear, but if you hover the arrea above the selected text you still get the name of the button ("Strikethrough", "insert/edit link"...) when you hover over it
- You can "add a block", that works without problem, like always has
- Title, permalink, featured image also work
- Publishing, saving drafgt, updating (in the lower, autohiding bar) works, editing it in the admin editor also works. 

So pretty much what doesn't work is the button bar as far as I know. 

![buttons](https://cloud.githubusercontent.com/assets/853760/12415072/d4893aaa-be99-11e5-954d-433ffb405197.jpg)

Thanks!

**Comment by iseulde** [comment]
Okay, can you pull the master branch without any fixes? So far I can only see that audio/video is broken and that there are some missing styles for the link toolbar. Please try with a default theme first, then maybe yours. Thanks a lot! Hope we can fix the few issues and push this to the plugin on .org so people can have it back.

**Comment by picajoso** [comment]
I'll try it and let you know how it goes. Great news!

**Comment by iseulde** [comment]
Thanks!

**Comment by iseulde** [comment]
Looks like everything is fixed. I will do some more tests, then release. If more things come up we can quickly do a new release.

**Comment by picajoso** [comment]
I've pulled the master branch and right now there are no changes for me but
this could be a cache issue. I've tried to clear caches and try different
browsers but at the moment the button bar is still missing. If it works for
you, though, I'm sure it'll be allright.

I've seen there is no "max" version in the package.json, I guess this is on
purpose, right?

Thanks for working on it Ella!

**Comment by potreb** [comment]
I have js error:

The content on the server and the content in the editor is different. This may be due to errors. - fee.js:487:5
ReferenceError: event is not defined - fee.js:636:4

**Comment by iseulde** [comment]
@picajoso Yes I've added it back. Can you see the toolbar in the dom (on the bottom). Can you figure out why it's not showing? What theme are you using?

**Comment by iseulde** [comment]
@potreb fixed ba27d902b75786f27758e4a26715e3bd012ec611

**Comment by picajoso** [comment]
Working nicely on WO 4.4.1. Awesome work @iseulde Thank you so much!!

**Comment by iseulde** [comment]
Okay, thanks for the feedback. Don't hesitate to open new issues.
